services:
  ros2:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    container_name: ros2_lidar_slam_bot

    network_mode: host

    privileged: true

    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: /tmp/.mutter-Xwaylandauth
      QT_X11_NO_MITSHM: "1"

    volumes:
      - ../ros_ws:/ros_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:/tmp/.mutter-Xwaylandauth:ro

    stdin_open: true
    tty: true

    working_dir: /ros_ws

    command: bash
